export const ANIMALS = [
  {
    id: 'dog',
    name: 'Buddy',
    species: 'Dog',
    emoji: '🐶',
    color: 'amber',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
    accentColor: 'bg-amber-400',
    textColor: 'text-amber-700',
    personality: 'Loyal & Playful',
    description: 'Always excited to play! Gets hungry fast but loves every minute with you.',
    drainRates: { hunger: 1.8, happiness: 1.2, energy: 1.4, cleanliness: 1.3 },
    favoriteAction: 'play',
  },
  {
    id: 'cat',
    name: 'Luna',
    species: 'Cat',
    emoji: '🐱',
    color: 'purple',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
    accentColor: 'bg-purple-400',
    textColor: 'text-purple-700',
    personality: 'Elegant & Mysterious',
    description: 'Independent and graceful. Prefers napping but appreciates a good cuddle.',
    drainRates: { hunger: 1.2, happiness: 0.9, energy: 0.8, cleanliness: 1.0 },
    favoriteAction: 'sleep',
  },
  {
    id: 'bunny',
    name: 'Cotton',
    species: 'Bunny',
    emoji: '🐰',
    color: 'pink',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
    accentColor: 'bg-pink-400',
    textColor: 'text-pink-700',
    personality: 'Energetic & Sweet',
    description: 'Bouncy and full of energy! Loves to hop around and needs lots of playtime.',
    drainRates: { hunger: 1.5, happiness: 1.6, energy: 1.5, cleanliness: 1.1 },
    favoriteAction: 'play',
  },
  {
    id: 'hamster',
    name: 'Peanut',
    species: 'Hamster',
    emoji: '🐹',
    color: 'orange',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
    accentColor: 'bg-orange-400',
    textColor: 'text-orange-700',
    personality: 'Tiny & Adventurous',
    description: 'A little foodie who loves exploring. Easy to care for but always hungry!',
    drainRates: { hunger: 2.0, happiness: 1.0, energy: 1.2, cleanliness: 0.9 },
    favoriteAction: 'feed',
  },
  {
    id: 'bird',
    name: 'Sky',
    species: 'Bird',
    emoji: '🐦',
    color: 'sky',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-300',
    accentColor: 'bg-sky-400',
    textColor: 'text-sky-700',
    personality: 'Cheerful & Social',
    description: 'Chirpy and bright! Needs constant company and gets sad when ignored.',
    drainRates: { hunger: 1.3, happiness: 1.8, energy: 1.1, cleanliness: 1.2 },
    favoriteAction: 'play',
  },
];

export const SHOP_ITEMS = [
  { id: 'apple',      category: 'food',      name: 'Fresh Apple',     emoji: '🍎', price: 15, effect: { hunger: 30 },                         description: 'A crunchy snack' },
  { id: 'cake',       category: 'food',      name: 'Birthday Cake',   emoji: '🎂', price: 35, effect: { hunger: 60, happiness: 20 },           description: 'A special treat!' },
  { id: 'carrot',     category: 'food',      name: 'Yummy Carrot',    emoji: '🥕', price: 10, effect: { hunger: 25 },                         description: 'Healthy and tasty' },
  { id: 'fish',       category: 'food',      name: 'Grilled Fish',    emoji: '🐟', price: 25, effect: { hunger: 45, energy: 15 },             description: 'Protein boost' },
  { id: 'ball',       category: 'toy',       name: 'Bouncy Ball',     emoji: '⚽', price: 20, effect: { happiness: 35, energy: -10 },         description: 'Hours of fun!' },
  { id: 'plushie',    category: 'toy',       name: 'Cozy Plushie',   emoji: '🧸', price: 30, effect: { happiness: 40, energy: 10 },           description: 'Cuddle buddy' },
  { id: 'puzzle',     category: 'toy',       name: 'Brain Puzzle',    emoji: '🧩', price: 45, effect: { happiness: 50, energy: -5 },          description: 'Mental stimulation' },
  { id: 'bow',        category: 'accessory', name: 'Cute Bow',        emoji: '🎀', price: 40, effect: { happiness: 25, cleanliness: 20 },      description: 'Looking fabulous' },
  { id: 'hat',        category: 'accessory', name: 'Party Hat',       emoji: '🎉', price: 50, effect: { happiness: 45 },                      description: 'Party time!' },
  { id: 'bubbles',    category: 'accessory', name: 'Bubble Bath',     emoji: '🛁', price: 30, effect: { cleanliness: 60, happiness: 15 },     description: 'Squeaky clean' },
];

export const MOODS = {
  ecstatic: { label: 'Ecstatic!',  emoji: '🥰', threshold: 85, coins: 5 },
  happy:    { label: 'Happy',      emoji: '😊', threshold: 70, coins: 3 },
  content:  { label: 'Content',    emoji: '🙂', threshold: 50, coins: 1 },
  neutral:  { label: 'Neutral',    emoji: '😐', threshold: 35, coins: 0 },
  sad:      { label: 'Sad',        emoji: '😢', threshold: 20, coins: 0 },
  sick:     { label: 'Sick',       emoji: '🤒', threshold: 0,  coins: 0 },
};

export const ACTION_CONFIGS = {
  feed:  { label: 'Feed',  emoji: '🍖', color: 'bg-orange-400 hover:bg-orange-500', effects: { hunger: 40, energy: 5 },              cost: null },
  play:  { label: 'Play',  emoji: '🎾', color: 'bg-pink-400   hover:bg-pink-500',   effects: { happiness: 40, energy: -15 },         cost: null },
  sleep: { label: 'Sleep', emoji: '😴', color: 'bg-indigo-400 hover:bg-indigo-500', effects: { energy: 50, happiness: 10 },          cost: null },
  bathe: { label: 'Bathe', emoji: '🛁', color: 'bg-sky-400    hover:bg-sky-500',    effects: { cleanliness: 50, happiness: 5 },      cost: null },
};

export const STAT_CONFIG = {
  hunger:      { label: 'Hunger',      emoji: '🍖', color: 'bg-orange-400', trackColor: 'bg-orange-100', low: 25, critical: 15 },
  happiness:   { label: 'Happiness',   emoji: '⭐', color: 'bg-pink-400',   trackColor: 'bg-pink-100',   low: 25, critical: 15 },
  energy:      { label: 'Energy',      emoji: '⚡', color: 'bg-yellow-400', trackColor: 'bg-yellow-100', low: 25, critical: 15 },
  cleanliness: { label: 'Cleanliness', emoji: '✨', color: 'bg-sky-400',    trackColor: 'bg-sky-100',    low: 25, critical: 15 },
};
